export const SIMULATION_THRESHOLD_RANDOM_EVENT = 75;
export const SIMULATION_THRESHOLD_EXPIRY = 3;
export const SIMULATION_THRESHOLD_HUNGER = 30;
export const SIMULATION_THRESHOLD_UNHAPPY = 30;
export const SIMULATION_THRESHOLD_DEFIANT_POOPING = 25;
